// Code generated by ogen, DO NOT EDIT.

package reviewerservice

import (
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	Error BadRequestErrorError `json:"error"`
}

// GetError returns the value of Error.
func (s *BadRequestError) GetError() BadRequestErrorError {
	return s.Error
}

// SetError sets the value of Error.
func (s *BadRequestError) SetError(val BadRequestErrorError) {
	s.Error = val
}

func (*BadRequestError) teamAddPostRes() {}

type BadRequestErrorError struct {
	// Внутренние коды ошибок:
	// - TEAM_EXISTS: команда сущесвует
	// - PR_EXISTS: Pull Request существует.
	Code BadRequestErrorErrorCode `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestErrorError) GetCode() BadRequestErrorErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestErrorError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestErrorError) SetCode(val BadRequestErrorErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestErrorError) SetMessage(val string) {
	s.Message = val
}

// Внутренние коды ошибок:
// - TEAM_EXISTS: команда сущесвует
// - PR_EXISTS: Pull Request существует.
type BadRequestErrorErrorCode string

const (
	BadRequestErrorErrorCodeTEAMEXISTS BadRequestErrorErrorCode = "TEAM_EXISTS"
	BadRequestErrorErrorCodePREXISTS   BadRequestErrorErrorCode = "PR_EXISTS"
)

// AllValues returns all BadRequestErrorErrorCode values.
func (BadRequestErrorErrorCode) AllValues() []BadRequestErrorErrorCode {
	return []BadRequestErrorErrorCode{
		BadRequestErrorErrorCodeTEAMEXISTS,
		BadRequestErrorErrorCodePREXISTS,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s BadRequestErrorErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case BadRequestErrorErrorCodeTEAMEXISTS:
		return []byte(s), nil
	case BadRequestErrorErrorCodePREXISTS:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *BadRequestErrorErrorCode) UnmarshalText(data []byte) error {
	switch BadRequestErrorErrorCode(data) {
	case BadRequestErrorErrorCodeTEAMEXISTS:
		*s = BadRequestErrorErrorCodeTEAMEXISTS
		return nil
	case BadRequestErrorErrorCodePREXISTS:
		*s = BadRequestErrorErrorCodePREXISTS
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	Error ConflictErrorError `json:"error"`
}

// GetError returns the value of Error.
func (s *ConflictError) GetError() ConflictErrorError {
	return s.Error
}

// SetError sets the value of Error.
func (s *ConflictError) SetError(val ConflictErrorError) {
	s.Error = val
}

func (*ConflictError) pullRequestCreatePostRes()   {}
func (*ConflictError) pullRequestReassignPostRes() {}

type ConflictErrorError struct {
	// Внутренние коды ошибок:
	// - PR_MERGED: Нельзя менять после MERGED
	// - NOT_ASSIGNED: Пользователь не был назначен ревьювером
	// - NO_CANDIDATE: Нет доступных кандидатов
	// - PR_EXISTS: Пулреквест уже есть.
	Code ConflictErrorErrorCode `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictErrorError) GetCode() ConflictErrorErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictErrorError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictErrorError) SetCode(val ConflictErrorErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictErrorError) SetMessage(val string) {
	s.Message = val
}

// Внутренние коды ошибок:
// - PR_MERGED: Нельзя менять после MERGED
// - NOT_ASSIGNED: Пользователь не был назначен ревьювером
// - NO_CANDIDATE: Нет доступных кандидатов
// - PR_EXISTS: Пулреквест уже есть.
type ConflictErrorErrorCode string

const (
	ConflictErrorErrorCodePRMERGED    ConflictErrorErrorCode = "PR_MERGED"
	ConflictErrorErrorCodeNOTASSIGNED ConflictErrorErrorCode = "NOT_ASSIGNED"
	ConflictErrorErrorCodeNOCANDIDATE ConflictErrorErrorCode = "NO_CANDIDATE"
	ConflictErrorErrorCodePREXISTS    ConflictErrorErrorCode = "PR_EXISTS"
)

// AllValues returns all ConflictErrorErrorCode values.
func (ConflictErrorErrorCode) AllValues() []ConflictErrorErrorCode {
	return []ConflictErrorErrorCode{
		ConflictErrorErrorCodePRMERGED,
		ConflictErrorErrorCodeNOTASSIGNED,
		ConflictErrorErrorCodeNOCANDIDATE,
		ConflictErrorErrorCodePREXISTS,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ConflictErrorErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ConflictErrorErrorCodePRMERGED:
		return []byte(s), nil
	case ConflictErrorErrorCodeNOTASSIGNED:
		return []byte(s), nil
	case ConflictErrorErrorCodeNOCANDIDATE:
		return []byte(s), nil
	case ConflictErrorErrorCodePREXISTS:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ConflictErrorErrorCode) UnmarshalText(data []byte) error {
	switch ConflictErrorErrorCode(data) {
	case ConflictErrorErrorCodePRMERGED:
		*s = ConflictErrorErrorCodePRMERGED
		return nil
	case ConflictErrorErrorCodeNOTASSIGNED:
		*s = ConflictErrorErrorCodeNOTASSIGNED
		return nil
	case ConflictErrorErrorCodeNOCANDIDATE:
		*s = ConflictErrorErrorCodeNOCANDIDATE
		return nil
	case ConflictErrorErrorCodePREXISTS:
		*s = ConflictErrorErrorCodePREXISTS
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	Error InternalServerErrorError `json:"error"`
}

// GetError returns the value of Error.
func (s *InternalServerError) GetError() InternalServerErrorError {
	return s.Error
}

// SetError sets the value of Error.
func (s *InternalServerError) SetError(val InternalServerErrorError) {
	s.Error = val
}

func (*InternalServerError) pullRequestCreatePostRes()   {}
func (*InternalServerError) pullRequestMergePostRes()    {}
func (*InternalServerError) pullRequestReassignPostRes() {}
func (*InternalServerError) teamAddPostRes()             {}
func (*InternalServerError) teamGetGetRes()              {}
func (*InternalServerError) usersGetReviewGetRes()       {}
func (*InternalServerError) usersSetIsActivePostRes()    {}

type InternalServerErrorError struct {
	// Внутренние коды ошибок:
	// - INTERNAL_ERROR - ошибка в работе сервиса.
	Code InternalServerErrorErrorCode `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerErrorError) GetCode() InternalServerErrorErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerErrorError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerErrorError) SetCode(val InternalServerErrorErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerErrorError) SetMessage(val string) {
	s.Message = val
}

// Внутренние коды ошибок:
// - INTERNAL_ERROR - ошибка в работе сервиса.
type InternalServerErrorErrorCode string

const (
	InternalServerErrorErrorCodeINTERNALERROR InternalServerErrorErrorCode = "INTERNAL_ERROR"
)

// AllValues returns all InternalServerErrorErrorCode values.
func (InternalServerErrorErrorCode) AllValues() []InternalServerErrorErrorCode {
	return []InternalServerErrorErrorCode{
		InternalServerErrorErrorCodeINTERNALERROR,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s InternalServerErrorErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case InternalServerErrorErrorCodeINTERNALERROR:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *InternalServerErrorErrorCode) UnmarshalText(data []byte) error {
	switch InternalServerErrorErrorCode(data) {
	case InternalServerErrorErrorCodeINTERNALERROR:
		*s = InternalServerErrorErrorCodeINTERNALERROR
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	Error NotFoundErrorError `json:"error"`
}

// GetError returns the value of Error.
func (s *NotFoundError) GetError() NotFoundErrorError {
	return s.Error
}

// SetError sets the value of Error.
func (s *NotFoundError) SetError(val NotFoundErrorError) {
	s.Error = val
}

func (*NotFoundError) pullRequestCreatePostRes()   {}
func (*NotFoundError) pullRequestMergePostRes()    {}
func (*NotFoundError) pullRequestReassignPostRes() {}
func (*NotFoundError) teamGetGetRes()              {}
func (*NotFoundError) usersGetReviewGetRes()       {}
func (*NotFoundError) usersSetIsActivePostRes()    {}

type NotFoundErrorError struct {
	// Внутренние коды ошибок:
	// - NOT_FOUND - значения нет.
	Code NotFoundErrorErrorCode `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundErrorError) GetCode() NotFoundErrorErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundErrorError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundErrorError) SetCode(val NotFoundErrorErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundErrorError) SetMessage(val string) {
	s.Message = val
}

// Внутренние коды ошибок:
// - NOT_FOUND - значения нет.
type NotFoundErrorErrorCode string

const (
	NotFoundErrorErrorCodeNOTFOUND NotFoundErrorErrorCode = "NOT_FOUND"
)

// AllValues returns all NotFoundErrorErrorCode values.
func (NotFoundErrorErrorCode) AllValues() []NotFoundErrorErrorCode {
	return []NotFoundErrorErrorCode{
		NotFoundErrorErrorCodeNOTFOUND,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s NotFoundErrorErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case NotFoundErrorErrorCodeNOTFOUND:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *NotFoundErrorErrorCode) UnmarshalText(data []byte) error {
	switch NotFoundErrorErrorCode(data) {
	case NotFoundErrorErrorCodeNOTFOUND:
		*s = NotFoundErrorErrorCodeNOTFOUND
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPullRequest returns new OptPullRequest with value set to v.
func NewOptPullRequest(v PullRequest) OptPullRequest {
	return OptPullRequest{
		Value: v,
		Set:   true,
	}
}

// OptPullRequest is optional PullRequest.
type OptPullRequest struct {
	Value PullRequest
	Set   bool
}

// IsSet returns true if OptPullRequest was set.
func (o OptPullRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPullRequest) Reset() {
	var v PullRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPullRequest) SetTo(v PullRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPullRequest) Get() (v PullRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPullRequest) Or(d PullRequest) PullRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTeam returns new OptTeam with value set to v.
func NewOptTeam(v Team) OptTeam {
	return OptTeam{
		Value: v,
		Set:   true,
	}
}

// OptTeam is optional Team.
type OptTeam struct {
	Value Team
	Set   bool
}

// IsSet returns true if OptTeam was set.
func (o OptTeam) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTeam) Reset() {
	var v Team
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTeam) SetTo(v Team) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTeam) Get() (v Team, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTeam) Or(d Team) Team {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUser returns new OptUser with value set to v.
func NewOptUser(v User) OptUser {
	return OptUser{
		Value: v,
		Set:   true,
	}
}

// OptUser is optional User.
type OptUser struct {
	Value User
	Set   bool
}

// IsSet returns true if OptUser was set.
func (o OptUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUser) Reset() {
	var v User
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUser) SetTo(v User) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUser) Get() (v User, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUser) Or(d User) User {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PullRequest
type PullRequest struct {
	PullRequestID   string            `json:"pull_request_id"`
	PullRequestName string            `json:"pull_request_name"`
	AuthorID        string            `json:"author_id"`
	Status          PullRequestStatus `json:"status"`
	// User_id назначенных ревьюверов (0..2).
	AssignedReviewers []string       `json:"assigned_reviewers"`
	CreatedAt         OptNilDateTime `json:"createdAt"`
	MergedAt          OptNilDateTime `json:"mergedAt"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequest) GetPullRequestID() string {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *PullRequest) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *PullRequest) GetAuthorID() string {
	return s.AuthorID
}

// GetStatus returns the value of Status.
func (s *PullRequest) GetStatus() PullRequestStatus {
	return s.Status
}

// GetAssignedReviewers returns the value of AssignedReviewers.
func (s *PullRequest) GetAssignedReviewers() []string {
	return s.AssignedReviewers
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PullRequest) GetCreatedAt() OptNilDateTime {
	return s.CreatedAt
}

// GetMergedAt returns the value of MergedAt.
func (s *PullRequest) GetMergedAt() OptNilDateTime {
	return s.MergedAt
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequest) SetPullRequestID(val string) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *PullRequest) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *PullRequest) SetAuthorID(val string) {
	s.AuthorID = val
}

// SetStatus sets the value of Status.
func (s *PullRequest) SetStatus(val PullRequestStatus) {
	s.Status = val
}

// SetAssignedReviewers sets the value of AssignedReviewers.
func (s *PullRequest) SetAssignedReviewers(val []string) {
	s.AssignedReviewers = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PullRequest) SetCreatedAt(val OptNilDateTime) {
	s.CreatedAt = val
}

// SetMergedAt sets the value of MergedAt.
func (s *PullRequest) SetMergedAt(val OptNilDateTime) {
	s.MergedAt = val
}

type PullRequestCreatePostCreated struct {
	Pr OptPullRequest `json:"pr"`
}

// GetPr returns the value of Pr.
func (s *PullRequestCreatePostCreated) GetPr() OptPullRequest {
	return s.Pr
}

// SetPr sets the value of Pr.
func (s *PullRequestCreatePostCreated) SetPr(val OptPullRequest) {
	s.Pr = val
}

func (*PullRequestCreatePostCreated) pullRequestCreatePostRes() {}

type PullRequestCreatePostReq struct {
	// Уникальный ID PR.
	PullRequestID string `json:"pull_request_id"`
	// Название PR.
	PullRequestName string `json:"pull_request_name"`
	// ID автора PR.
	AuthorID string `json:"author_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestCreatePostReq) GetPullRequestID() string {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *PullRequestCreatePostReq) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *PullRequestCreatePostReq) GetAuthorID() string {
	return s.AuthorID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestCreatePostReq) SetPullRequestID(val string) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *PullRequestCreatePostReq) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *PullRequestCreatePostReq) SetAuthorID(val string) {
	s.AuthorID = val
}

type PullRequestMergePostOK struct {
	Pr OptPullRequest `json:"pr"`
}

// GetPr returns the value of Pr.
func (s *PullRequestMergePostOK) GetPr() OptPullRequest {
	return s.Pr
}

// SetPr sets the value of Pr.
func (s *PullRequestMergePostOK) SetPr(val OptPullRequest) {
	s.Pr = val
}

func (*PullRequestMergePostOK) pullRequestMergePostRes() {}

type PullRequestMergePostReq struct {
	// Уникальный ID PR.
	PullRequestID string `json:"pull_request_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestMergePostReq) GetPullRequestID() string {
	return s.PullRequestID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestMergePostReq) SetPullRequestID(val string) {
	s.PullRequestID = val
}

type PullRequestReassignPostOK struct {
	Pr PullRequest `json:"pr"`
	// User_id нового ревьювера.
	ReplacedBy string `json:"replaced_by"`
}

// GetPr returns the value of Pr.
func (s *PullRequestReassignPostOK) GetPr() PullRequest {
	return s.Pr
}

// GetReplacedBy returns the value of ReplacedBy.
func (s *PullRequestReassignPostOK) GetReplacedBy() string {
	return s.ReplacedBy
}

// SetPr sets the value of Pr.
func (s *PullRequestReassignPostOK) SetPr(val PullRequest) {
	s.Pr = val
}

// SetReplacedBy sets the value of ReplacedBy.
func (s *PullRequestReassignPostOK) SetReplacedBy(val string) {
	s.ReplacedBy = val
}

func (*PullRequestReassignPostOK) pullRequestReassignPostRes() {}

type PullRequestReassignPostReq struct {
	PullRequestID string `json:"pull_request_id"`
	OldUserID     string `json:"old_user_id"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestReassignPostReq) GetPullRequestID() string {
	return s.PullRequestID
}

// GetOldUserID returns the value of OldUserID.
func (s *PullRequestReassignPostReq) GetOldUserID() string {
	return s.OldUserID
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestReassignPostReq) SetPullRequestID(val string) {
	s.PullRequestID = val
}

// SetOldUserID sets the value of OldUserID.
func (s *PullRequestReassignPostReq) SetOldUserID(val string) {
	s.OldUserID = val
}

// Ref: #/components/schemas/PullRequestShort
type PullRequestShort struct {
	PullRequestID   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	AuthorID        string                 `json:"author_id"`
	Status          PullRequestShortStatus `json:"status"`
}

// GetPullRequestID returns the value of PullRequestID.
func (s *PullRequestShort) GetPullRequestID() string {
	return s.PullRequestID
}

// GetPullRequestName returns the value of PullRequestName.
func (s *PullRequestShort) GetPullRequestName() string {
	return s.PullRequestName
}

// GetAuthorID returns the value of AuthorID.
func (s *PullRequestShort) GetAuthorID() string {
	return s.AuthorID
}

// GetStatus returns the value of Status.
func (s *PullRequestShort) GetStatus() PullRequestShortStatus {
	return s.Status
}

// SetPullRequestID sets the value of PullRequestID.
func (s *PullRequestShort) SetPullRequestID(val string) {
	s.PullRequestID = val
}

// SetPullRequestName sets the value of PullRequestName.
func (s *PullRequestShort) SetPullRequestName(val string) {
	s.PullRequestName = val
}

// SetAuthorID sets the value of AuthorID.
func (s *PullRequestShort) SetAuthorID(val string) {
	s.AuthorID = val
}

// SetStatus sets the value of Status.
func (s *PullRequestShort) SetStatus(val PullRequestShortStatus) {
	s.Status = val
}

type PullRequestShortStatus string

const (
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
)

// AllValues returns all PullRequestShortStatus values.
func (PullRequestShortStatus) AllValues() []PullRequestShortStatus {
	return []PullRequestShortStatus{
		PullRequestShortStatusOPEN,
		PullRequestShortStatusMERGED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PullRequestShortStatus) MarshalText() ([]byte, error) {
	switch s {
	case PullRequestShortStatusOPEN:
		return []byte(s), nil
	case PullRequestShortStatusMERGED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PullRequestShortStatus) UnmarshalText(data []byte) error {
	switch PullRequestShortStatus(data) {
	case PullRequestShortStatusOPEN:
		*s = PullRequestShortStatusOPEN
		return nil
	case PullRequestShortStatusMERGED:
		*s = PullRequestShortStatusMERGED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PullRequestStatus string

const (
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
)

// AllValues returns all PullRequestStatus values.
func (PullRequestStatus) AllValues() []PullRequestStatus {
	return []PullRequestStatus{
		PullRequestStatusOPEN,
		PullRequestStatusMERGED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PullRequestStatus) MarshalText() ([]byte, error) {
	switch s {
	case PullRequestStatusOPEN:
		return []byte(s), nil
	case PullRequestStatusMERGED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PullRequestStatus) UnmarshalText(data []byte) error {
	switch PullRequestStatus(data) {
	case PullRequestStatusOPEN:
		*s = PullRequestStatusOPEN
		return nil
	case PullRequestStatusMERGED:
		*s = PullRequestStatusMERGED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Team
type Team struct {
	// Уникальное имя команды.
	TeamName string       `json:"team_name"`
	Members  []TeamMember `json:"members"`
}

// GetTeamName returns the value of TeamName.
func (s *Team) GetTeamName() string {
	return s.TeamName
}

// GetMembers returns the value of Members.
func (s *Team) GetMembers() []TeamMember {
	return s.Members
}

// SetTeamName sets the value of TeamName.
func (s *Team) SetTeamName(val string) {
	s.TeamName = val
}

// SetMembers sets the value of Members.
func (s *Team) SetMembers(val []TeamMember) {
	s.Members = val
}

func (*Team) teamGetGetRes() {}

type TeamAddPostCreated struct {
	Team OptTeam `json:"team"`
}

// GetTeam returns the value of Team.
func (s *TeamAddPostCreated) GetTeam() OptTeam {
	return s.Team
}

// SetTeam sets the value of Team.
func (s *TeamAddPostCreated) SetTeam(val OptTeam) {
	s.Team = val
}

func (*TeamAddPostCreated) teamAddPostRes() {}

// Ref: #/components/schemas/TeamMember
type TeamMember struct {
	// Уникальный ID пользователя.
	UserID string `json:"user_id"`
	// Имя пользователя.
	Username string `json:"username"`
	// Активен ли пользователь.
	IsActive bool `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *TeamMember) GetUserID() string {
	return s.UserID
}

// GetUsername returns the value of Username.
func (s *TeamMember) GetUsername() string {
	return s.Username
}

// GetIsActive returns the value of IsActive.
func (s *TeamMember) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *TeamMember) SetUserID(val string) {
	s.UserID = val
}

// SetUsername sets the value of Username.
func (s *TeamMember) SetUsername(val string) {
	s.Username = val
}

// SetIsActive sets the value of IsActive.
func (s *TeamMember) SetIsActive(val bool) {
	s.IsActive = val
}

// Ref: #/components/schemas/User
type User struct {
	// Уникальный ID пользователя.
	UserID string `json:"user_id"`
	// Имя пользователя.
	Username string `json:"username"`
	// Название команды пользователя.
	TeamName string `json:"team_name"`
	// Активен ли пользователь.
	IsActive bool `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *User) GetUserID() string {
	return s.UserID
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// GetTeamName returns the value of TeamName.
func (s *User) GetTeamName() string {
	return s.TeamName
}

// GetIsActive returns the value of IsActive.
func (s *User) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *User) SetUserID(val string) {
	s.UserID = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

// SetTeamName sets the value of TeamName.
func (s *User) SetTeamName(val string) {
	s.TeamName = val
}

// SetIsActive sets the value of IsActive.
func (s *User) SetIsActive(val bool) {
	s.IsActive = val
}

type UsersGetReviewGetOK struct {
	UserID       string             `json:"user_id"`
	PullRequests []PullRequestShort `json:"pull_requests"`
}

// GetUserID returns the value of UserID.
func (s *UsersGetReviewGetOK) GetUserID() string {
	return s.UserID
}

// GetPullRequests returns the value of PullRequests.
func (s *UsersGetReviewGetOK) GetPullRequests() []PullRequestShort {
	return s.PullRequests
}

// SetUserID sets the value of UserID.
func (s *UsersGetReviewGetOK) SetUserID(val string) {
	s.UserID = val
}

// SetPullRequests sets the value of PullRequests.
func (s *UsersGetReviewGetOK) SetPullRequests(val []PullRequestShort) {
	s.PullRequests = val
}

func (*UsersGetReviewGetOK) usersGetReviewGetRes() {}

type UsersSetIsActivePostOK struct {
	User OptUser `json:"user"`
}

// GetUser returns the value of User.
func (s *UsersSetIsActivePostOK) GetUser() OptUser {
	return s.User
}

// SetUser sets the value of User.
func (s *UsersSetIsActivePostOK) SetUser(val OptUser) {
	s.User = val
}

func (*UsersSetIsActivePostOK) usersSetIsActivePostRes() {}

type UsersSetIsActivePostReq struct {
	// Идентификатор пользователя.
	UserID   string `json:"user_id"`
	IsActive bool   `json:"is_active"`
}

// GetUserID returns the value of UserID.
func (s *UsersSetIsActivePostReq) GetUserID() string {
	return s.UserID
}

// GetIsActive returns the value of IsActive.
func (s *UsersSetIsActivePostReq) GetIsActive() bool {
	return s.IsActive
}

// SetUserID sets the value of UserID.
func (s *UsersSetIsActivePostReq) SetUserID(val string) {
	s.UserID = val
}

// SetIsActive sets the value of IsActive.
func (s *UsersSetIsActivePostReq) SetIsActive(val bool) {
	s.IsActive = val
}
